# Sử dụng Node.js làm base image
FROM node:18

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào container
COPY package.json /app/package.json

# Cài đặt các dependencies
RUN npm install

# Kiểm tra xem `vite` có khả dụng không
RUN npx vite --version

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Expose port 3000 cho ứng dụng React
EXPOSE 3000

# Chạy ứng dụng ReactJS bằng Vite
CMD ["npm", "run", "dev", "--", "--host"]
