version: '3'

services:
  # Service cho Laravel (Backend)
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Truy cập Laravel qua http://localhost:8080
    volumes:
      # - ./nginx/laravel.conf:/etc/nginx/sites-enabled/default
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    networks:
      - app-network
  # MySQL container
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Service cho React (Frontend)
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - laravel
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: "production"
      MEILI_MASTER_KEY: "P_bKjtUOiDg6h01Ex75vwkQvbtm7W21EkMZOz0d3IcE"
    volumes:
      - ./backend/meilisearch:/meili_data
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
